export type ThreadlyPost = {
  pt: string;
  en: string;
  clip?: { poster: string; src: string };
};

export const threadlyPosts: ThreadlyPost[] = [
  { pt: 'o contador foi de 7 para 11 e depois 17 no mesmo dia. alguém avisa quando os números resolverem parar quietos?', en: 'the count went from 7 to 11 and then 17 in one day. let me know when the numbers decide to sit still?', clip: { poster: 'assets/threadly/rede-oceanica.jpg', src: 'assets/threadly/rede-oceanica.mp4' } },
  { pt: 'o clique da unidade DT virou o som oficial da aula hoje. metade da sala olhando para o teto, metade atualizando o feed.', en: 'the DT unit clicking became the official sound of class today. half the room stared at the ceiling, half refreshed the feed.', clip: { poster: 'assets/threadly/distant-trees.jpg', src: 'assets/threadly/distant-trees.mp4' } },
  { pt: 'sete navios parados e eu ainda tenho prova amanhã. prioridades muito mal distribuídas.', en: 'seven ships stopped and I still have a test tomorrow. priorities are wildly misplaced.' },
  { pt: 'se mais uma pessoa disser “meu tio trabalha no porto”, eu vou pedir nome, turno e crachá.', en: 'if one more person says “my uncle works at the port,” I am asking for a name, shift and badge.' },
  { pt: 'troquei de canal três vezes e ganhei três causas diferentes. excelente serviço.', en: 'I changed channels three times and got three different causes. excellent service.' },
  { pt: 'a neve parou. meu tênis molhado não recebeu o memorando.', en: 'the snow stopped. my wet shoes did not get the memo.' },
  { pt: 'propulsão responde, navio não anda. eu oficialmente não entendo nada e pelo menos admito.', en: 'propulsion responds, ship does not move. I officially understand nothing and at least I admit it.' },
  { pt: 'a padaria abriu no horário. finalmente uma instituição em que ainda posso confiar.', en: 'the bakery opened on time. finally, an institution I can still trust.' },
  { pt: 'minha mãe desligou a TV no jantar e, por vinte minutos, o oceano teve que se virar sem a gente.', en: 'my mother turned off the TV at dinner and, for twenty minutes, the ocean had to manage without us.' },
  { pt: 'o ônibus chegou atrasado e ninguém culpou os navios. crescimento coletivo.', en: 'the bus was late and nobody blamed the ships. collective growth.' },
  { pt: '“em análise” já virou uma resposta para tudo, inclusive para eu não ter feito a tarefa.', en: '“under review” is now an answer to everything, including why I did not do my homework.' },
  { pt: 'ninguém sabe se são casos novos ou confirmações atrasadas, mas todo mundo sabe discutir o número.', en: 'nobody knows whether they are new cases or late confirmations, but everybody knows how to argue about the number.' },
  { pt: 'o cachorro ficou cinco minutos encarando a neve como se também esperasse um boletim.', en: 'the dog stared at the snow for five minutes like he was waiting for a bulletin too.' },
  { pt: 'café frio, luvas úmidas e cobertura ao vivo. bela manhã para estar acordada.', en: 'cold coffee, damp gloves and live coverage. lovely morning to be awake.' },
  { pt: 'eu só queria saber se a aula seria cancelada. recebi uma explicação de vinte minutos sobre satélites.', en: 'I only wanted to know whether class was canceled. I got a twenty-minute explanation about satellites.' },
  { pt: 'quem inventou a teoria do hacker já apareceu com alguma prova ou seguimos trabalhando só com confiança?', en: 'has the person who invented the hacker theory produced any evidence, or are we still running on trust?' },
  { pt: 'a televisão da sala foi desligada e os celulares começaram a vibrar em coro. silêncio muito eficiente.', en: 'the classroom TV was turned off and every phone started buzzing together. very effective silence.' },
  { pt: 'o melhor resumo que ouvi hoje foi “não sabemos”. curto, honesto e surpreendentemente raro.', en: 'the best summary I heard today was “we do not know.” short, honest and surprisingly rare.' },
  { pt: 'minha torrada queimou enquanto eu atualizava a contagem. não posso provar relação entre os eventos.', en: 'my toast burned while I refreshed the count. I cannot prove the events are related.' },
  { pt: 'o porto daqui está funcionando, antes que alguém transforme uma foto antiga em alerta urgente.', en: 'the port here is operating, before someone turns an old photo into an urgent alert.' },
  { pt: 'a parte mais estranha é ver todo mundo continuar o dia e olhar para a tela a cada dois minutos.', en: 'the strangest part is watching everyone continue their day and check a screen every two minutes.' },
  { pt: 'meu professor pediu fontes. metade da turma descobriu que “vi num comentário” não conta.', en: 'my teacher asked for sources. half the class learned that “saw it in a comment” does not count.' },
  { pt: 'a hipótese magnética parece ótima até alguém perguntar o que ela explica exatamente.', en: 'the magnetic hypothesis sounds great until someone asks what exactly it explains.' },
  { pt: 'não sei o que está acontecendo no oceano, mas sei que o pão saiu quente às 7h12.', en: 'I do not know what is happening in the ocean, but I know the bread came out warm at 7:12.' },
  { pt: 'a rua está normal demais para uma manhã em que todo mundo só fala de navio.', en: 'the street feels far too normal for a morning when everybody is talking about ships.' },
  { pt: 'meu pai ouviu “falha eletrônica” e começou a revisar cada aparelho da casa. socorro.', en: 'my father heard “electronic failure” and started checking every device in the house. help.' },
  { pt: 'a neve fina é bonita até entrar na meia. opinião técnica depois de caminhar até a escola.', en: 'fine snow is pretty until it gets into your sock. technical opinion after walking to school.' },
  { pt: '17 é confirmação oficial ou só o número que chegou primeiro no feed? pergunta sincera.', en: 'is 17 an official confirmation or just the number that reached the feed first? honest question.' },
  { pt: 'um colega desenhou a rota dos navios no caderno e esqueceu completamente a matéria da prova.', en: 'a classmate drew the ships’ routes in his notebook and completely forgot the test material.' },
  { pt: 'desliguei as notificações por uma hora. quando voltei, o mundo ainda estava aqui e havia 63 mensagens.', en: 'I turned notifications off for an hour. when I came back, the world was still here and there were 63 messages.' },
  { pt: 'se a causa ainda não foi confirmada, talvez a gente possa parar de escrever “confirmado” em letras enormes.', en: 'if the cause has not been confirmed, maybe we can stop writing “confirmed” in enormous letters.' },
  { pt: 'a manutenção do DT terminou e ninguém ganhou dispensa. essa sim foi a notícia ruim da escola.', en: 'DT maintenance ended and nobody got the day off. that was the real bad news at school.' },
  { pt: 'tem gente contando navios como quem acompanha placar. não é um jogo, pessoal.', en: 'people are counting ships like they are following a score. this is not a game, people.' },
  { pt: 'minha avó assistiu a todos os boletins e concluiu que os apresentadores também não sabem. impecável.', en: 'my grandmother watched every bulletin and concluded the presenters do not know either. flawless.' },
  { pt: 'um minuto de respeito ao café que ficou esquecido ao lado da TV desde o primeiro alerta.', en: 'a moment of respect for the coffee forgotten beside the TV since the first alert.' },
  { pt: 'o motorista do ônibus pediu para ninguém mostrar mais atualização enquanto ele dirige. justo.', en: 'the bus driver asked everyone to stop showing him updates while he drives. fair.' },
  { pt: 'vi uma foto de um cargueiro imóvel e dez explicações incompatíveis embaixo dela.', en: 'I saw one photo of a stopped cargo ship and ten incompatible explanations beneath it.' },
  { pt: 'hoje aprendi que “o sistema responde” não significa necessariamente “está tudo funcionando”.', en: 'today I learned that “the system responds” does not necessarily mean “everything is working.”' },
  { pt: 'as lojas abriram, as aulas começaram e o feed decidiu que era o fim do mundo. rotina equilibrada.', en: 'shops opened, classes started and the feed decided it was the end of the world. balanced routine.' },
  { pt: 'minha irmã está anotando cada contagem. eu estou anotando quantas vezes ela diz “eu avisei”.', en: 'my sister is writing down every count. I am writing down how often she says “I told you.”' },
  { pt: 'satélite, hacker, eletrônica, magnetismo. falta só alguém culpar o clima e completar a coleção.', en: 'satellite, hacker, electronics, magnetism. someone only needs to blame the weather to complete the set.' },
  { pt: 'a cantina lotada e todo mundo segurando o celular na mesma altura. parecia reunião sem convite.', en: 'the cafeteria was packed and everyone held their phone at the same height. it looked like an uninvited meeting.' },
  { pt: 'não compartilhem áudio sem origem. principalmente se começa com “um conhecido meu ouviu”.', en: 'do not share audio with no source. especially if it starts with “someone I know heard.”' },
  { pt: 'a professora tentou voltar à matéria e alguém perguntou se navio parado cai na prova.', en: 'the teacher tried to return to the lesson and someone asked whether stopped ships would be on the test.' },
  { pt: 'meu guarda-chuva venceu a neve, mas perdeu para o vento antes da esquina.', en: 'my umbrella beat the snow but lost to the wind before the corner.' },
  { pt: 'até agora a única coisa consistente nas reportagens é que a causa continua incerta.', en: 'so far the only consistent thing in the reports is that the cause remains uncertain.' },
  { pt: 'o padeiro disse que as pessoas compraram o dobro de pão. espero que seja fome, não pânico.', en: 'the baker said people bought twice as much bread. I hope it is hunger, not panic.' },
  { pt: 'se ninguém consegue mover as embarcações, imagino o tamanho da fila de formulários.', en: 'if nobody can move the vessels, imagine the size of the paperwork queue.' },
  { pt: 'abri o aplicativo para ver amigos e saí sabendo mais palpites sobre propulsão do que queria.', en: 'I opened the app to see friends and left knowing more propulsion guesses than I wanted.' },
  { pt: 'a palavra “anomalia” está fazendo um trabalho pesado demais hoje.', en: 'the word “anomaly” is doing far too much work today.' },
  { pt: 'o vizinho limpou a calçada enquanto ouvia o boletim no volume máximo. informação comunitária.', en: 'the neighbor cleared the sidewalk while playing the bulletin at full volume. community information.' },
  { pt: 'queria uma atualização que dissesse só o que mudou desde a última, sem quinze minutos de suspense.', en: 'I want an update that only says what changed since the last one, without fifteen minutes of suspense.' },
  { pt: 'o grupo da turma passou de exercícios para teorias marítimas em menos de três mensagens.', en: 'the class group went from exercises to maritime theories in fewer than three messages.' },
  { pt: 'meu irmão apostou que a próxima contagem será maior. eu preferia que isso não virasse aposta.', en: 'my brother bet the next count will be higher. I would rather this did not become a bet.' },
  { pt: 'a equipe do porto merece café. provavelmente muito café.', en: 'the port crew deserves coffee. probably a lot of coffee.' },
  { pt: 'li “interferência solar” e olhei pela janela como se o sol fosse prestar esclarecimentos.', en: 'I read “solar interference” and looked out the window as if the sun would issue a statement.' },
  { pt: 'os painéis do ônibus demoraram para atualizar e alguém já chamou de sinal. às vezes é só o ônibus.', en: 'the bus displays updated late and someone already called it a sign. sometimes it is just the bus.' },
  { pt: 'minha única teoria sólida: ninguém vai prestar atenção na última aula.', en: 'my only solid theory: nobody will pay attention in the last class.' },
  { pt: 'uma pessoa perguntou se devia cancelar uma viagem terrestre por causa dos navios. respirem.', en: 'someone asked whether to cancel a land trip because of the ships. breathe.' },
  { pt: 'o termo “caso” está sendo usado para tanta coisa que já não sei se todos contam igual.', en: 'the word “case” is being used for so many things that I no longer know whether everyone counts the same way.' },
  { pt: 'a TV repetiu a mesma imagem quatro vezes e meu avô percebeu nas quatro.', en: 'the TV repeated the same image four times and my grandfather noticed every time.' },
  { pt: 'fui comprar luvas e a fila inteira discutia oceano. saí com luvas e zero certezas.', en: 'I went to buy gloves and the whole line was discussing the ocean. I left with gloves and zero certainty.' },
  { pt: 'não é porque uma teoria parece interessante que ela virou explicação.', en: 'a theory does not become an explanation just because it sounds interesting.' },
  { pt: 'o silêncio depois que desligaram a televisão durou exatamente oito segundos.', en: 'the silence after they turned off the television lasted exactly eight seconds.' },
  { pt: 'alguém levou um rádio para a escola. agora temos notificações em versão alta.', en: 'someone brought a radio to school. now we have notifications in loud mode.' },
  { pt: 'minha mãe mandou levar casaco e eu achei exagero. retiro oficialmente o que pensei.', en: 'my mother told me to wear a coat and I thought she was exaggerating. I officially withdraw that thought.' },
  { pt: 'qualquer atualização com cinco pontos de exclamação perde minha confiança automaticamente.', en: 'any update with five exclamation marks automatically loses my trust.' },
  { pt: 'o porto pediu calma. o feed interpretou como oportunidade para falar mais alto.', en: 'the port asked for calm. the feed took it as an opportunity to shout louder.' },
  { pt: 'estou esperando alguém explicar a diferença entre parado, sem rota e sem comunicação.', en: 'I am waiting for someone to explain the difference between stopped, off course and out of communication.' },
  { pt: 'meu colega diz que entende motores. ontem ele não conseguiu abrir um pote.', en: 'my classmate says he understands engines. yesterday he could not open a jar.' },
  { pt: 'a sala inteira atualizou o número ao mesmo tempo e ainda assim apareceram três versões.', en: 'the whole class refreshed the number at once and somehow got three versions.' },
  { pt: 'pelo menos o aquecimento voltou antes que meus dedos pedissem demissão.', en: 'at least the heating came back before my fingers resigned.' },
  { pt: 'não vou chamar de padrão até alguém mostrar um padrão. parece razoável.', en: 'I will not call it a pattern until someone shows a pattern. seems reasonable.' },
  { pt: 'a manhã teve neve, atraso e navios imóveis. meu café teve a coragem de acabar.', en: 'the morning had snow, delays and stopped ships. my coffee had the nerve to run out.' },
  { pt: 'um perfil postou “fontes no porto” e apagou quando pediram detalhes. anotado.', en: 'an account posted “port sources” and deleted it when asked for details. noted.' },
  { pt: 'as embarcações respondem aos comandos, mas não avançam. isso é estranho o bastante sem enfeite.', en: 'the vessels respond to commands but do not advance. that is strange enough without embellishment.' },
  { pt: 'a padaria criou um pão chamado “ancorado”. rápido demais, porém admito que foi engraçado.', en: 'the bakery made a loaf called “anchored.” far too soon, but I admit it was funny.' },
  { pt: 'prometi estudar depois do próximo boletim. já passaram quatro boletins.', en: 'I promised to study after the next bulletin. four bulletins have passed.' },
  { pt: 'o cachorro voltou do passeio coberto de neve e claramente mais informado do que eu.', en: 'the dog came back from his walk covered in snow and clearly better informed than me.' },
  { pt: 'não, uma tela piscando na escola não prova interferência em escala oceânica.', en: 'no, a screen flickering at school does not prove interference on an oceanic scale.' },
  { pt: 'se houver coletiva, alguém pode perguntar primeiro o que mudou de verdade?', en: 'if there is a briefing, can someone first ask what actually changed?' },
  { pt: 'meus pais discordam sobre a causa e concordam que eu devo lavar a louça. injusto.', en: 'my parents disagree about the cause and agree that I should wash the dishes. unfair.' },
  { pt: 'a frase “ainda não há confirmação” deveria vir antes do título, não no fim.', en: 'the sentence “there is no confirmation yet” should come before the headline, not at the end.' },
  { pt: 'o frio deixou todo mundo andando rápido, menos os navios. desculpa.', en: 'the cold made everyone move faster, except the ships. sorry.' },
  { pt: 'hoje a aula de ciências virou uma longa conversa sobre como não confundir hipótese com resposta.', en: 'today science class became a long conversation about not confusing a hypothesis with an answer.' },
  { pt: 'tem um barco comum passando ao longe e já vi três pessoas filmando. nem tudo é ocorrência.', en: 'there is an ordinary boat passing in the distance and I already saw three people filming. not everything is an incident.' },
  { pt: 'minha notificação dizia 11, o jornal dizia 17 e o professor disse para guardar o celular.', en: 'my notification said 11, the news said 17 and the teacher said to put my phone away.' },
  { pt: 'ninguém no meu grupo terminou a apresentação, mas agora todos têm opinião sobre magnetismo.', en: 'nobody in my group finished the presentation, but now everyone has an opinion about magnetism.' },
  { pt: 'o jantar foi a primeira hora do dia sem uma contagem nova. recomendo.', en: 'dinner was the first hour of the day without a new count. highly recommended.' },
  { pt: 'a loja da esquina segue aberta e vendendo chocolate quente. informação verificada pessoalmente.', en: 'the corner shop is still open and selling hot chocolate. personally verified information.' },
  { pt: 'uma manchete perguntou “o que vem agora?”. eu também, manchete.', en: 'a headline asked “what comes next?” same question, headline.' },
  { pt: 'talvez a gente devesse ouvir mais quem está examinando os navios e menos quem descobriu o assunto hoje.', en: 'maybe we should listen more to the people examining the ships and less to those who found the topic today.' },
  { pt: 'o corredor ficou quieto durante o boletim e voltou ao caos no intervalo. normalidade restaurada.', en: 'the hallway went quiet during the bulletin and returned to chaos at break. normality restored.' },
  { pt: 'coloquei o celular no bolso e ouvi a neve sob os sapatos. melhor atualização da tarde.', en: 'I put my phone in my pocket and heard the snow under my shoes. best update of the afternoon.' },
  { pt: 'meu tio realmente trabalha no porto e a única mensagem dele foi “estou ocupado”. fonte confiável.', en: 'my uncle actually works at the port and his only message was “I am busy.” reliable source.' },
  { pt: 'se os números subirem de novo, por favor publiquem horário e origem junto. não custa.', en: 'if the numbers rise again, please publish the time and source with them. it is not hard.' },
  { pt: 'a bateria acabou no meio da cobertura e foi a pausa mais tranquila que tive hoje.', en: 'my battery died in the middle of the coverage and it was the calmest break I had today.' },
  { pt: 'até o professor conferiu uma notificação escondido. ninguém comentou por solidariedade.', en: 'even the teacher checked a notification in secret. nobody mentioned it out of solidarity.' },
  { pt: 'não há resposta ainda. isso é frustrante, mas inventar uma não melhora nada.', en: 'there is no answer yet. that is frustrating, but inventing one does not improve anything.' },
  { pt: 'o céu clareou um pouco e a cidade pareceu lembrar que o dia ainda estava acontecendo.', en: 'the sky cleared a little and the city seemed to remember the day was still happening.' },
];
