export type ThreadlyPost = { pt: string; en: string; clip?: { poster: string; src: string } };

const posts: Array<[string, string]> = [
  ['Passei a manhã acompanhando as atualizações e ainda não entendi se o número mudou ou se só confirmaram casos antigos.', 'I spent the morning following the updates and I still do not know whether the number changed or they only confirmed older cases.'],
  ['A unidade DT da sala voltou a funcionar. Agora só falta a turma parar de reclamar do frio.', 'The classroom DT unit is working again. Now the class only needs to stop complaining about the cold.'],
  ['Alguém sabe se amanhã vai nevar de novo? Tenho que sair cedo.', 'Does anyone know if it will snow again tomorrow? I have to leave early.'],
  ['A fila da padaria estava enorme hoje. Acho que todo mundo resolveu tomar café fora.', 'The bakery line was huge today. I think everyone decided to have breakfast out.'],
  ['Se sair uma atualização confiável sobre os navios, me marca. Cansei de abrir postagem sem fonte.', 'Tag me if a reliable update about the ships comes out. I am tired of opening posts with no source.'],
  ['Minha mãe mandou eu largar o celular e ir jantar. Pela primeira vez hoje, ela tinha toda a razão.', 'My mother told me to put the phone down and have dinner. For the first time today, she was completely right.'],
  ['A professora desligou a televisão, mas ninguém conseguiu prestar atenção depois.', 'The teacher turned off the television, but nobody managed to focus afterward.'],
  ['Cheguei na escola com a meia molhada. O resto do dia foi uma longa consequência dessa decisão.', 'I got to school with a wet sock. The rest of the day was one long consequence of that decision.'],
  ['Tem café novo na cantina e ele é surpreendentemente bom.', 'There is new coffee in the cafeteria and it is surprisingly good.'],
  ['Meu ônibus atrasou de novo. Não tem relação com o oceano; ele só atrasa mesmo.', 'My bus was late again. It has nothing to do with the ocean; it is just always late.'],
  ['A rua ficou bonita com a neve, mas eu gostaria de admirar de dentro de casa.', 'The street looks beautiful in the snow, but I would rather admire it from inside.'],
  ['Alguém da turma entendeu o exercício três? Eu parei de fingir que sim.', 'Did anyone in class understand exercise three? I have stopped pretending I did.'],
  ['O cachorro se recusou a sair por causa do frio. Sinceramente, respeito.', 'The dog refused to go out because of the cold. Honestly, I respect that.'],
  ['Meu pai está vendo o mesmo boletim pela quarta vez. Nada mudou desde a primeira.', 'My father is watching the same bulletin for the fourth time. Nothing has changed since the first.'],
  ['Hoje todo mundo tinha uma teoria. Ninguém tinha uma fonte.', 'Everyone had a theory today. Nobody had a source.'],
  ['Se os sistemas dos navios respondem, por que eles continuam parados? Pergunta real, sem teoria maluca.', 'If the ships’ systems respond, why are they still stopped? Real question, no wild theory.'],
  ['Fiz chocolate quente e esqueci na mesa até ficar frio. Excelente planejamento.', 'I made hot chocolate and forgot it on the table until it went cold. Excellent planning.'],
  ['A neve já parou por aqui. A calçada continua um desastre.', 'The snow has stopped here. The sidewalk is still a mess.'],
  ['A aula continuou normalmente, tirando o fato de que ninguém estava realmente prestando atenção.', 'Class continued as usual, except nobody was actually paying attention.'],
  ['Não compartilhem aquele áudio. Ele já apareceu com três histórias diferentes sobre a origem.', 'Do not share that audio. It has already appeared with three different stories about where it came from.'],
  ['A padaria da esquina ainda tem pão quente. Essa é a única atualização que posso confirmar pessoalmente.', 'The corner bakery still has warm bread. That is the only update I can personally confirm.'],
  ['Prometi que estudaria depois do próximo boletim. Foi uma péssima forma de adiar a tarefa.', 'I promised I would study after the next bulletin. It was a terrible way to postpone homework.'],
  ['Meu irmão está anotando cada número que aparece na televisão. Não sei o que ele pretende fazer com isso.', 'My brother is writing down every number shown on television. I have no idea what he plans to do with it.'],
  ['O céu abriu um pouco no fim da tarde. Ainda está frio demais.', 'The sky cleared a little in the late afternoon. It is still far too cold.'],
  ['Alguém deixou uma luva no ônibus da linha central. Entreguei para o motorista.', 'Someone left a glove on the central bus. I gave it to the driver.'],
  ['A cantina mudou o cardápio sem avisar e eu só descobri quando cheguei no balcão.', 'The cafeteria changed the menu without warning and I only found out at the counter.'],
  ['Vi gente filmando um barco comum porque acharam que era outro caso. Calma.', 'I saw people filming an ordinary boat because they thought it was another case. Calm down.'],
  ['Minha avó resumiu a cobertura de hoje com “eles ainda não sabem”. Está certa.', 'My grandmother summarized today’s coverage with “they still do not know.” She is right.'],
  ['A manutenção do DT terminou antes da segunda aula. Não, isso não cancelou a prova.', 'DT maintenance ended before second period. No, that did not cancel the test.'],
  ['Fiquei uma hora sem olhar as notificações e foi a melhor hora da manhã.', 'I went an hour without checking notifications and it was the best hour of the morning.'],
  ['O grupo da turma começou falando da tarefa e terminou discutindo satélites. Como sempre, ninguém fez a tarefa.', 'The class group started with homework and ended up discussing satellites. As usual, nobody did the homework.'],
  ['Alguém pode mandar a foto do quadro? A minha ficou toda tremida.', 'Can someone send a picture of the board? Mine came out completely blurry.'],
  ['As lojas daqui abriram normalmente hoje. Vi duas postagens dizendo o contrário.', 'The shops here opened normally today. I saw two posts claiming otherwise.'],
  ['Não sei quem precisa ler isso, mas hipótese não é confirmação.', 'I do not know who needs to read this, but a hypothesis is not a confirmation.'],
  ['O motorista pediu para pararem de mostrar notícias enquanto ele dirigia. Pedido bastante razoável.', 'The driver asked people to stop showing him news while he was driving. A very reasonable request.'],
  ['Esqueci meu casaco na escola. Se alguém achar um azul no segundo corredor, é meu.', 'I left my coat at school. If anyone finds a blue one in the second hallway, it is mine.'],
  ['Minha irmã colocou o rádio na cozinha e agora a casa inteira sabe cada vez que não há novidade.', 'My sister put the radio in the kitchen and now the whole house hears whenever there is no news.'],
  ['A rua está mais silenciosa que o normal hoje ou sou eu prestando atenção demais?', 'Is the street quieter than usual today, or am I paying too much attention?'],
  ['Ainda não disseram o que causou as paralisações. O resto é gente completando o silêncio.', 'They still have not said what caused the stoppages. Everything else is people filling the silence.'],
  ['Acabou o pão antes de eu chegar. Meu dia começou oficialmente errado.', 'They ran out of bread before I arrived. My day officially started wrong.'],
  ['A TV da recepção ficou ligada a manhã inteira. A mesma imagem apareceu tantas vezes que decorei.', 'The reception TV stayed on all morning. The same image appeared so many times I memorized it.'],
  ['Meu colega disse que entende de motores. Ontem ele não conseguiu consertar o zíper da mochila.', 'My classmate says he understands engines. Yesterday he could not fix his backpack zipper.'],
  ['A neve derreteu na minha gola e eu passei o caminho inteiro reclamando sozinha.', 'Snow melted down my collar and I complained to myself the whole way.'],
  ['Se alguém tiver o resumo da aula de ciências, manda no grupo. O resumo da aula, não do telejornal.', 'If anyone has the science lesson notes, send them to the group. The lesson, not the news coverage.'],
  ['Meu pai acha que é falha eletrônica. Minha tia acha que é atividade solar. Eu acho que os dois deveriam esperar.', 'My father thinks it is an electronic failure. My aunt thinks it is solar activity. I think they should both wait.'],
  ['O cachorro voltou do passeio coberto de neve e foi direto para a cama.', 'The dog came back from his walk covered in snow and went straight to bed.'],
  ['Hoje o intervalo pareceu curto demais. Talvez porque passamos metade dele olhando para uma tela.', 'Break felt too short today. Maybe because we spent half of it looking at a screen.'],
  ['A contagem mudou de novo ou estão repetindo a atualização da tarde?', 'Did the count change again, or are they repeating the afternoon update?'],
  ['Tem uma diferença enorme entre “não encontraram falha” e “sabem o que aconteceu”.', 'There is a huge difference between “they found no fault” and “they know what happened.”'],
  ['A loja da esquina está vendendo chocolate quente até mais tarde esta semana.', 'The corner shop is selling hot chocolate later this week.'],
  ['Meu celular vibrou no meio da prova e a sala inteira olhou. Era só o grupo da família.', 'My phone buzzed during the test and the whole room looked. It was only the family group.'],
  ['Alguém mais sente que hoje durou uns três dias?', 'Does anyone else feel like today lasted about three days?'],
  ['O painel do ônibus demorou para atualizar. Isso acontece toda semana, não transformem em teoria.', 'The bus display updated late. That happens every week, do not turn it into a theory.'],
  ['Minha mãe fez torradas enquanto a TV falava dos navios. Foi uma manhã estranhamente normal.', 'My mother made toast while the TV talked about the ships. It was a strangely normal morning.'],
  ['Não achei nenhuma confirmação sobre portos fechados. Se alguém tiver, manda o link original.', 'I could not find any confirmation about closed ports. If anyone has one, send the original link.'],
  ['A professora pediu fontes e metade das teorias da sala desapareceu na hora.', 'The teacher asked for sources and half the class theories disappeared immediately.'],
  ['A luz do fim da tarde na neve estava bonita. Tirei uma foto e ficou horrível.', 'The late afternoon light on the snow was beautiful. I took a picture and it looked awful.'],
  ['Estou aceitando recomendações de música para estudar. Preciso de algo que vença as notificações.', 'I am taking music recommendations for studying. I need something that can beat the notifications.'],
  ['Se vocês não sabem de onde veio uma imagem, não usem como prova de nada.', 'If you do not know where an image came from, do not use it as proof of anything.'],
  ['Meu avô perguntou por que continuam chamando especialistas se ninguém tem resposta. Eu não soube responder.', 'My grandfather asked why they keep calling experts if nobody has an answer. I did not know what to say.'],
  ['Aquecimento funcionando, café quente e nenhuma prova amanhã. Finalmente uma noite boa.', 'Heating working, hot coffee and no test tomorrow. Finally a good evening.'],
  ['Passei no porto de longe e parecia tudo mais calmo do que no feed.', 'I passed near the port and everything looked calmer than it does on the feed.'],
  ['O jornal repetiu que a causa continua em análise. É pouco, mas pelo menos é honesto.', 'The news repeated that the cause is still under review. It is not much, but at least it is honest.'],
  ['Alguém pegou meu caderno por engano depois da aula. Tem uma capa verde e meu nome dentro.', 'Someone took my notebook by mistake after class. It has a green cover and my name inside.'],
  ['Meu irmão apostou qual seria o próximo número. Falei para ele parar; isso não é placar.', 'My brother tried to bet on the next number. I told him to stop; this is not a score.'],
  ['A calçada em frente à escola está escorregando muito. Cuidado na saída.', 'The sidewalk in front of school is very slippery. Be careful on your way out.'],
  ['Desliguei a televisão durante o jantar. As notícias continuaram existindo sem a nossa ajuda.', 'I turned off the television during dinner. The news kept existing without our help.'],
  ['Tenho a impressão de que todo mundo ouviu “sem explicação” e decidiu oferecer uma.', 'I get the feeling everyone heard “no explanation” and decided to provide one.'],
  ['A biblioteca estava quase vazia hoje. Melhor lugar para terminar a tarefa.', 'The library was almost empty today. Best place to finish homework.'],
  ['Vi a mesma foto com três horários diferentes. Confiram antes de compartilhar.', 'I saw the same photo with three different times. Check before sharing.'],
  ['Meu café esfriou enquanto eu respondia mensagens. De novo.', 'My coffee went cold while I answered messages. Again.'],
  ['A turma conseguiu ficar em silêncio por quase um minuto quando ligaram a televisão.', 'The class managed to stay quiet for almost a minute when they turned on the television.'],
  ['Ainda tem neve acumulada nos carros daqui. Levem luvas se forem sair cedo.', 'There is still snow piled on cars here. Wear gloves if you are leaving early.'],
  ['Não aconteceu nada novo nos últimos vinte minutos. Vocês podem parar de atualizar por vinte segundos.', 'Nothing new has happened in the last twenty minutes. You can stop refreshing for twenty seconds.'],
  ['O pão doce da cantina melhorou ou eu estava com muita fome?', 'Did the cafeteria sweet bread get better, or was I just very hungry?'],
  ['Minha tia mandou um texto enorme sobre magnetismo e terminou com “não sei se é isso”.', 'My aunt sent a huge message about magnetism and ended it with “I do not know if that is it.”'],
  ['As aulas de amanhã continuam no mesmo horário, segundo o aviso da escola.', 'Tomorrow’s classes are still at the usual time, according to the school notice.'],
  ['Eu só queria abrir o aplicativo e ver fotos de cachorro. Hoje não foi o dia.', 'I only wanted to open the app and see dog pictures. Today was not the day.'],
  ['Se forem passar pela praça, o caminho perto da fonte está menos escorregadio.', 'If you are crossing the square, the path near the fountain is less slippery.'],
  ['A melhor resposta que ouvi hoje foi “a gente ainda não sabe”.', 'The best answer I heard today was “we still do not know.”'],
  ['Alguém topa estudar junto depois da aula? Sozinho eu vou acabar acompanhando notícia de novo.', 'Anyone want to study together after class? Alone, I will end up following the news again.'],
  ['Meu pai deixou o café no carro e só percebeu quando chegou ao trabalho.', 'My father left his coffee in the car and only noticed when he got to work.'],
  ['Os navios continuam parados. Não vi nenhuma informação nova além disso desde o último boletim.', 'The ships are still stopped. I have not seen any new information beyond that since the last bulletin.'],
  ['A neve no telhado começou a derreter e está pingando bem na entrada. Cuidado.', 'The snow on the roof has started melting and it is dripping right by the entrance. Careful.'],
  ['Aquele perfil apagou a postagem depois que pediram a fonte. Era o mínimo.', 'That account deleted the post after people asked for a source. That was the least they could do.'],
  ['A cantina está aceitando encomenda de pão para amanhã. Avisando porque hoje acabou cedo.', 'The cafeteria is taking bread orders for tomorrow. Sharing because it sold out early today.'],
  ['Minha bateria acabou no caminho para casa. Foi uma pausa involuntária, mas necessária.', 'My battery died on the way home. It was an involuntary but necessary break.'],
  ['O professor também olhou uma notificação escondido. Ninguém falou nada.', 'The teacher checked a notification in secret too. Nobody said anything.'],
  ['Se a próxima atualização só repetir a anterior, vou terminar meu trabalho e voltar depois.', 'If the next update only repeats the last one, I am finishing my work and coming back later.'],
  ['O ônibus estava tão quente que meus óculos embaçaram quando entrei.', 'The bus was so warm that my glasses fogged up when I got in.'],
  ['Minha irmã disse que não estava preocupada e depois atualizou o jornal cinco vezes.', 'My sister said she was not worried and then refreshed the news five times.'],
  ['A escola pediu para não espalharem boatos nos grupos. Já estava passando da hora.', 'The school asked people not to spread rumors in group chats. It was overdue.'],
  ['Tem sopa em casa e eu passei o dia inteiro pensando nisso.', 'There is soup at home and I have been thinking about it all day.'],
  ['Não sei se são novos casos ou novas confirmações. Se alguém souber de verdade, explica sem gritar.', 'I do not know whether they are new cases or new confirmations. If someone truly knows, explain it without shouting.'],
  ['A rua voltou a ficar movimentada depois que a neve parou.', 'The street got busy again after the snow stopped.'],
  ['Perdi o primeiro ônibus porque voltei para buscar as luvas. Ainda acho que fiz a escolha certa.', 'I missed the first bus because I went back for my gloves. I still think I made the right choice.'],
  ['O grupo da família finalmente mudou de assunto. Agora estão discutindo o jantar.', 'The family group finally changed the subject. Now they are arguing about dinner.'],
  ['As imagens do cargueiro são estranhas o bastante. Não precisa inventar legenda.', 'The cargo ship images are strange enough. There is no need to invent a caption.'],
  ['Vou deixar as notificações desligadas até amanhã. Se algo realmente mudar, alguém vai me contar.', 'I am leaving notifications off until tomorrow. If something really changes, someone will tell me.'],
  ['Boa noite para quem ainda precisa terminar a tarefa que fingiu esquecer o dia inteiro.', 'Good night to everyone who still has to finish the homework they pretended to forget all day.'],
];

export const threadlyPosts: ThreadlyPost[] = posts.map(([pt, en], index) => ({
  pt,
  en,
  ...(index === 0 ? { clip: { poster: 'assets/threadly/rede-oceanica.jpg', src: 'assets/threadly/rede-oceanica.mp4' } } : {}),
  ...(index === 1 ? { clip: { poster: 'assets/threadly/distant-trees.jpg', src: 'assets/threadly/distant-trees.mp4' } } : {}),
}));
